name: Deploy test_app

on:
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      rollback:
        description: 'Run rollback script manually'
        required: false
        default: 'false'

jobs:
  deploy:
    if: ${{ github.event.inputs.rollback != 'true' }}
    runs-on: ubuntu-22.04
    env:
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      ANSIBLE_BECOME_PASS: ${{ secrets.SERVER_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH Deploy
        id: deploy_step
        uses: appleboy/ssh-action@master
        with:
          host: 91.240.254.52
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: GIT_USERNAME,GIT_TOKEN,ANSIBLE_BECOME_PASS
          script: |
            cd /home/root/apps/test_app
            bash ./deploy.sh

  rollback:
    if: ${{ failure() && github.event.inputs.rollback != 'true' }}
    needs: deploy
    runs-on: ubuntu-22.04
    env:
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH Rollback
        uses: appleboy/ssh-action@master
        with:
          host: 91.240.254.52
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: GIT_USERNAME,GIT_TOKEN
          script: |
            cd /home/root/apps/test_app
            bash ./rollback.sh
