name: Deploy test_app

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    env:
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
      ANSIBLE_BECOME_PASS: ${{ secrets.SERVER_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 91.240.254.52
          username: root
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: GIT_USERNAME,GIT_TOKEN,ANSIBLE_BECOME_PASS
          script: |
            echo "Ожидание появления deploy.sh в /home/root/apps/test_app"
            for i in {1..10}; do
              if [ -f "/home/root/apps/test_app/deploy.sh" ]; then
                echo "✔ Найден deploy.sh"
                break
              fi
              echo "Ожидание 1 секунду..."
              sleep 1
            done
            if [ ! -f "/home/root/apps/test_app/deploy.sh" ]; then
              echo "Файл deploy.sh не найден. Ошибка."
              exit 1
            fi
            chmod +x /home/root/apps/test_app/deploy.sh
            cd /home/root/apps/test_app
            ./deploy.sh
