name: Deploy dasdas

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: SSH Deploy
        uses: appleboy/ssh-action@master
        with:
          host: 89.179.242.33
          username: ubuntu
          password: ${{ secrets.SERVER_PASSWORD }}
          envs: GIT_USERNAME,GIT_TOKEN
          script: |
            cd /home/ubuntu/apps/dasdas
            bash ./deploy.sh
    env:
      GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
